### ISSUE TITLE
Missing proper licensing

### ISSUE THREAD

**Issue by iakov** [andrey-terekhov/RuC#14]
LICENSE file that covers all the new sources is the Apache 2.0, but headers in files states that all rights (well... which, actually?) are reserved by Andrey Terekhov. This is an open source project, and at least we can view and share. I hope this confusion is just a result of an unfinished licensing work. Please, change headers according to LICENSE. Probably, it is not a critical Apache License 2.0 violation actually, but nevertheless ...

**Comment by Victor-Y-Fadeev** [comment]
Done.
