### ISSUE TITLE
Faulty canonicalization of absolute paths on *nix

### ISSUE THREAD

**Issue by maximmenshikov** [andrey-terekhov/RuC#73]
The canonicalization process driven by ws_unix_path() overwrites the first symbol of a correct unix path.
/home/user/src/RuC/tests/executable/functions/main/russian.c
->
home/user/src/RuC/tests/executable/functions/main/russian.c
so compiler doesn't work when absolute path is passed

**Comment by Victor-Y-Fadeev** [comment]
Fixed.
