### ISSUE TITLE
MIPS opcode definitions are not compatible with C++

### ISSUE THREAD

**Issue by maximmenshikov** [andrey-terekhov/RuC#76]
MIPS opcodes set in lib/compiler/defs.h are not compatible with C++ compilers. I suggest to turn them into enumeration with appropriate prefix.
e.g.:
_deps/ruc-src/libs/compiler/defs.h:544:9: error: "and" cannot be used as a macro name as it is an operator in C++
  544 | #define and 96  // and rd, rs, rt  rd = ts & rt
      |         ^~~
_deps/ruc-src/libs/compiler/defs.h:545:9: error: "or" cannot be used as a macro name as it is an operator in C++
  545 | #define or 97  // or rd, rs, rt  rd = ts | rt
      |         ^~
_deps/ruc-src/libs/compiler/defs.h:546:9: error: "xor" cannot be used as a macro name as it is an operator in C++
  546 | #define xor 98  // xor rd, rs, rt  rd = ts ^ rt
      |         ^~~

**Comment by Victor-Y-Fadeev** [comment]
Why do you required to compatible with C++ compilers?

**Comment by maximmenshikov** [comment]
Invocation from C++ projects is much more wide-spread than invocation from C. My project is one of such cases.
Hint: RuC is _already_ full of sugar to support invocation from C++ (note extern "C" in all headers). The MIPS opcode definition problem is the only one breaking this popular use case.

**Comment by Victor-Y-Fadeev** [comment]
Ok, It will be added with MIPS refactoring.

**Comment by bugdea1er** [comment]
Closed in #122
