### ISSUE TITLE
repr_get_spelling() writes result to offset 2

### ISSUE THREAD

**Issue by maximmenshikov** [andrey-terekhov/RuC#80]
repr_get_spelling() writes result to offset 2, e.g. with node of TFuncdef type:

  int ident = node_get_arg(node, 0);
  int repr = ident_get_repr(sx, ident);
  char32_t name[oops];
  repr_get_spelling(sx, repr, name);

name[0] = 0, name[1] = 0, name[2...] = { 'm', 'a', 'i', 'n', '\0' };

**Comment by Victor-Y-Fadeev** [comment]
This function will be removed, use `repr_get_ident`/`repr_get_name`.
